name: CI

on:
  push:
    branches:
      - main
      - dev
      - '**'
  pull_request:
    branches:
      - main
      - dev
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306

    steps:
      - name: Check out repository
        uses: actions/checkout@v4  

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, mysql, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --ansi

      - name: Generate key
        run: php artisan key:generate

      - name: Create .env file
        run: cp .env.example .env

      - name: Configure database
        run: |
          php artisan config:cache
          php artisan migrate --force

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit

      - name: Run PHP CS Fixer
        run: composer fix
